# Generated by Django 5.2 on 2025-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
