# Generated by Django 5.2 on 2025-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_address_room_location_remove_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='landlord_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='landlord_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
